### ISSUE TITLE
BadRequestError: Accept SecurityContext

### ISSUE THREAD

**Issue by acecoder93** [jlguenego/node-expose-sspi#10]
I am running a simple script using the latest version and as you mentioned previously, that sometimes I need it to initialize and then rerun it for it to actually work.

I followed your instructions, and this is what happened (Running 32bit nodejs on Windows 64bit OS):

1. Ran Script
2. Go to localhost:3000
3. Receive error "BadRequestError: Error while doing SSO: AcceptSecurityContext: SECURITY_STATUS incorrect(<0): (error code: 0x80090308) **The token supplied to the function is invalid"**
4. Refresh the page to go to localhost:3000
5. Receive status code 200 and successfully retrieve AD information via "NTLM". In addition to this success message, I receive a different error message: 
"BadRequestError: Error while doing SSO: AcceptSecurityContext: SECURITY_STATUS incorrect(<0): (error code: 0x80090301) **The handle specified is invalid"**. 

I am not sure why I am receiving two responses at once (success + error message).

Please note that with the previous version of the library,  this would not occur. It would either consistently error or it would work upon initially running the script.

**Comment by jlguenego** [comment]
Yes, I saw the bug and I am able to reproduce it. I investigate.

**Comment by jlguenego** [comment]
I saw the reason. Shame on me... In `auth.ts` I forgot to release the schManager with the cookieToken...
I do not understand even why it was working in x64... ;)
My fault...

Corrected in 0.1.26. Please test and close issue.

**Comment by acecoder93** [comment]
Thank you for resolving this bug and releasing a new version! I was able to test it and it worked successfully without any issues.
