### ISSUE TITLE
FR: Improving Active Directory integration

### ISSUE THREAD

**Issue by tomer953** [jlguenego/node-expose-sspi#113]
**Feature Request**
Create ActiveDirectory Module for a better integration \ use with AD.

Hi,
I just found that your library suits most of my cases, and for years I used a lot of workarounds that now can be achieved in few lines of codes - so first - huge thanks!

anyway, I'm using [activedirectory2](https://www.npmjs.com/package/activedirectory2) package,
which is very old, but does the work.
the thing is that we need to pass the username and password to the package config, so I prefer using your solution in order to avoid that.

therefore, I have some feature requests for improving the AD integration:
1. create some common functions like in `activedirectory2` ie:
 - findUser(username)
 - findGroup(groupName)
 - isUserMemberOf(user, group)
 etc..
2. custom entity parser same as  `activedirectory2` - allowing us to grab the buffer from `thumbnailPhoto` property, which now returns `undefined`
3. better typing for the AD results, ie maybe we can pass an object with our AD properties with description, and insert this typing dynamiclly to the result of the AD User result  
4. pack into AD module or something easier than: `const { getUser } = require("node-expose-sspi/dist/sso/userdb");`

Thank you for your hard work.

**Comment by jlguenego** [comment]
I forgot to indicate that node-expose-sspi exposes all ActiveDirectory API. It is called Win32 ADSI. You have it in node in this library.
Look at the test file regarding ADSI.
https://github.com/jlguenego/node-expose-sspi/blob/master/test/adsi.spec.ts
