### ISSUE TITLE
BadRequestError Issues

### ISSUE THREAD

**Issue by acecoder93** [jlguenego/node-expose-sspi#12]
As I am implementing node-expose-sspi and running a script on Windows OS (64-bit) with nodejs (32-bit), I am encountering the following errors:

Please note that whitelisting has not been applied.

This error occurs after I manually insert my valid credentials into the pop-up:
1. "BadRequestError: Error while doing SSO: AcceptSecurityContext error: SEC_E_LOGON_DENIED"

This error occurs where I attempt multiple requests to the domain:
2. "BadRequestError: Error while doing SSO: AcceptSecurityContext: SECURITY_STATUS incorrect (<0): (error code: 0x80090310) The message supplied for verification is out of sequence."

**Comment by jlguenego** [comment]
Yes, it may be normal when you enter "incorrectly" your credentials.

When you have a popup window, it means you are connecting via NTLM. If you try to reach the webserver outside of "localhost", then the popup arises and you need to enter your windows account credentials.

A window account credential is:
login: `<NETBIOSdomain>\<username>` (or `<username>@<domain>`)
password: `<your windows account password>`

<NETBIOSdomain> is the shortname of the domain.
<domain> is the long name of the domain

If you want to connect with a local account, <domain> must be the hostname.

For example, on my computer, the hostname is CHOUCHOU, and is joined to the windows domain called jlg.local (netbios name : JLG)

So If I connect with my domain account (username = jlguenego), I will do:
login: `JLG\jlguenego` (or `jlguenego@jlg.local`)
password: `<mysecret...>`

If I connect with my local account (username = jlouis), I will do:
login: `CHOUCHOU\jlouis`
password: `<myjlouissecretpassword>`

**Comment by jlguenego** [comment]
Note that on a production system, you should try to use Kerberos as it is much more secure than NTLM.

**Comment by AdamMarton** [comment]
I'm having a similar(?) issue:

`Error: AcceptSecurityContext: SECURITY_STATUS incorrect (<0): (error code: 0x80090308) The token supplied to the function is invalid`

I can give you more details, if needed @jlguenego

**Comment by jlguenego** [comment]
@AdamMarton 
This error is not the same, it looks like the token provided by your client is not good. Please be sure to run the last version (0.1.27) and please open a different issue if needed. In the issue, please add a maximum of contextual info by setting up the DEBUG mode (`set DEBUG=node-expose-sspi:*`) and show the traces. Also specify your OS, node version and context. Thanks ;)

**Comment by acecoder93** [comment]
@jlguenego - Thank you for your help! The issue was more regarding how I was handling the session. One thing that did help was disabling the "cookies" config within the sso.auth(). There is no further issue, so I will proceed by closing this issue.

**Comment by jlguenego** [comment]
ok ;)
