### ISSUE TITLE
BadRequestError: Malformed authentication token NTLM <token>

### ISSUE THREAD

**Issue by AdamMarton** [jlguenego/node-expose-sspi#14]
Hi @jlguenego,

Sorry for spamming your issue tracker, but was able to tweak my web server differently, so I gave it another shot.

What is happening I'm getting the following error in IE 11.3630.x:

```
BadRequestError: Malformed authentication token NTLM <token>
    at Object.<anonymous> (C:\<path>\node_modules\node-expose-sspi\dist\sso\auth.js:100:80)
    at step (C:\<path>\node_modules\node-expose-sspi\dist\sso\auth.js:33:23)
    at Object.next (C:\<path>\node_modules\node-expose-sspi\dist\sso\auth.js:14:53)
    at C:\<path>\node_modules\node-expose-sspi\dist\sso\auth.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\<path>\node_modules\node-expose-sspi\dist\sso\auth.js:4:12)
    at C:\<path>\node_modules\node-expose-sspi\dist\sso\auth.js:86:31
    at C:\<path>\node_modules\node-expose-sspi\dist\sso\auth.js:180:15
    at Layer.handle [as handle_request] (C:\<path>\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\<path>\node_modules\express\lib\router\index.js:317:13)
```

But I'm able to authenticate myself from the very same machine in the terminal by:

```
Invoke-WebRequest -uri <URL> -UseDefaultCredentials
```

Could you please advise what went wrong?

**Comment by jlguenego** [comment]
Hi,

I did not test with IE11. I am going to reproduce your error and come back to you.
Have you tested with Edge, Chrome or Firefox ?

**Comment by AdamMarton** [comment]
Hi @jlguenego,

Tested with Firefox (applied tweaks [described here](https://www.npmjs.com/package/node-expose-sspi#firefox)), but it didn't worked. My use case is very specific though, it should work with IE :(

**Comment by jlguenego** [comment]
Hi @AdamMarton ,

I did a test with IE11 (11.1098.17763.0) and the very simple server was working.
(tested with localhost only, on a windows domain)
May be there is something wrong with your environment ? Please give me more detailed about your environment and the versions, type of software you are using.

**Comment by jlguenego** [comment]
Closing this defect.
