### ISSUE TITLE
Logon dialog prompt when accessing server from IP on local machine or other machines on network?

### ISSUE THREAD

**Issue by overgaardmorten** [jlguenego/node-expose-sspi#19]
Hi,

We have been trying this module running the react-sample. 
Environment: Windows Domain running NTLM

**Dialog prompt: Steps to reproduce**
1) Start backend server and frontend
2) Start Chrome (83.0.4103.97 - running on windows)  or IE 11
2) Access backend server through IP from local machine. http://xx.xxx.xx:3000
3) Or access backend server from another machine on the network
4) Login prompt is presented to the user

IS this expected behavior. I would expect the user to just be logged in throug SSO. Using the same browser to access sharepoint sites on the same domain works with SSO -  without having to log in. 

**SSO working as expecting **
1) Start backend server and frontend
2) Start Chrome (83.0.4103.97 - running on windows)  
2) Access backend server through localhost from local machine. http://localhost:3000
3) User is getting logged in as expected

Kind regards Morten

**Comment by giuliohome** [comment]
I can't see how to add a site trusted sites in chrome or the new chromium edge on windows 10 enterprise e and anyway it is something that is not working out of the box in our intranet in a typical test case. I aslo see that it works for localhost (which is useless) while the logon dialog keeps prompting when accessing a server that is not localhost. It seems a serious problem to me.

**Comment by sissilab** [comment]
@giuliohome  Hi, have you solved this problem which the logon dialog keeps prompting in ip access mode?

**Comment by giuliohome** [comment]
@sissilab I think so, but consider also that at the time I forked a few repos from here and applied some changes...

e.g. https://github.com/jlguenego/angular-sso-example/compare/master...giuliohome:angular-sso-example:master 

Let me see, if I quickly find also my comments, I'll edit and pingback here. 
Yep, see https://github.com/jlguenego/node-expose-sspi/issues/117 (and maybe also https://github.com/simonbuchan/native-users-node/pull/3)
