### ISSUE TITLE
is there any configuration available?

### ISSUE THREAD

**Issue by rbartholomay** [jlguenego/node-expose-sspi#2]
Hi!

First:  This is absolut amazing!! And very useful!

Is there any configuration available. For example i don´t need the groups, so the library must/should not asked about them?

Bye, René

**Comment by jlguenego** [comment]
Nope... ;)
I will do it because if users has 1000 groups, this array could be very big.

**Comment by jlguenego** [comment]
It is done in 0.1.4. You can use the `AuthOptions` in the `sso.auth(options)` function.

Exemple (in TS) :

```
import express = require('express');
import { sso } from 'node-expose-sspi';

const app = express();

app.use(
  sso.auth({ useGroups: false, useOwner: false, useActiveDirectory: false })
);

app.use((req, res, next) => {
  res.json({
    sso: req.sso,
  });
});

app.listen(3001, () => console.log('Server started on port 3001'));
```

**Comment by jlguenego** [comment]
Tell me if I can close this issue. Thanks ;)

**Comment by rbartholomay** [comment]
hmm.... no - in my case it crashes :-|  So i try your example...

in 0.1.3  i get all groups, owner an activedirectory. All runs fine...   

then i install 0.1.4 and use this:

```
const express = require('express');
const { sso } = require('node-expose-sspi');

const app = express();

app.use(
  sso.auth({ useGroups: true, useOwner: true, useActiveDirectory: true })
);

app.use((req, res, next) => {
  res.json({
    sso: req.sso,
  });
});

app.listen(3001, () => console.log('Server started on port 3001'));
```
I get user, groups, owner but no activedirectory and the express server is terminated. 

Any idea?

**Comment by jlguenego** [comment]
Ouch... I look at it.

**Comment by jlguenego** [comment]
I have replicated the bug. I see the crash on my platform. I investigate the cause.

**Comment by jlguenego** [comment]
Fixed. Can you test the 0.1.6 version ?

Again, sorry for the inconvenience.

**Comment by rbartholomay** [comment]
👍  runs fine!  And much faster!!!

Thanks!

**Comment by jlguenego** [comment]
Good !!! :heart_eyes:
