### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by aateeque** [jlguenego/node-expose-sspi#22]
I get this error when I try to call `InitializeSecurityContext(arg)` with the following arg:

```json
{
  "credential": "XXXXXXX",
  "targetName": "HTTP/<hostname>",
  "cbMaxToken": 65791,
  "serverSecurityContext": {
    "SecBufferDesc": {
      "ulVersion": 0,
      "buffers": [
        {}
      ]
    }
  },
  "contextHandle": "XXXXXXXXX",
  "targetDataRep": "SECURITY_NATIVE_DREP"
}
```

*Exception*

```
Error: Cannot InitializeSecurityContext: secStatus = (error code: 0x80090308) The token supplied to the function is invalid
```

**Comment by jlguenego** [comment]
I will investigate this during the next week-end.

**Comment by aateeque** [comment]
Awesome, thanks. Let me give more context to help; I have a IIS server with win auth that I am trying to do a Negotiate with. I've taken the the `[client](https://github.com/jlguenego/node-expose-sspi/blob/bad9e5c135c889021d104934d5919dd5f05778f6/src/sso/client.ts)` basically; so the sequence in [`handleAuth()`](https://github.com/jlguenego/node-expose-sspi/blob/bad9e5c135c889021d104934d5919dd5f05778f6/src/sso/client.ts#L171):

1. On [L209](https://github.com/jlguenego/node-expose-sspi/blob/bad9e5c135c889021d104934d5919dd5f05778f6/src/sso/client.ts#L209) `credInput` is `{"packageName":"Negotiate","credentialUse":"SECPKG_CRED_OUTBOUND"}`
2. And [`AcquireCredentialsHandle`](https://github.com/jlguenego/node-expose-sspi/blob/bad9e5c135c889021d104934d5919dd5f05778f6/src/sso/client.ts#L209) returns  `{"credential":"0x0000000002b81420.0x000000000254dea0","tsExpiry":"+030828-09-13T02:48:05.000Z"}`
3. `packageInfo` in the [next line](https://github.com/jlguenego/node-expose-sspi/blob/bad9e5c135c889021d104934d5919dd5f05778f6/src/sso/client.ts#L211) is: 
`{"fCapabilities":"0x00083bb3","wVersion":1,"wRPCID":9,"cbMaxToken":65791,"Name":"Negotiate","Comment":"Microsoft Package Negotiator"}`
4. Then the `targetName` is `HTTP/{{REDACTED_FQDN}}` which is resolved from the URL in the `resource` argument
5. Next we `sspi.InitializeSecurityContext()` for `input` 
`{"credential":"0x0000000002b81420.0x000000000254dea0","targetName":"HTTP/{{REDACTED_FQDN}}","cbMaxToken":65791,"targetDataRep":"SECURITY_NATIVE_DREP"}`
6. Which sets `clientSecurityContext ` to: `{"contextHandle":"0x0000000002691620.0x000000000254dea0","contextAttr":["ISC_RET_INTERMEDIATE_RETURN"],"SECURITY_STATUS":"SEC_I_CONTINUE_NEEDED","SecBufferDesc":{"ulVersion":0,"buffers":[{}]}}`
7. So following this setup, the first [`fetch`](https://github.com/jlguenego/node-expose-sspi/blob/bad9e5c135c889021d104934d5919dd5f05778f6/src/sso/client.ts#L231) we make returns a `401` with a `www-authenticate Negotiate`
8. **Note** I get `Negotiate, NTLM` in `www-authenticate` on this first request
9. So I changed the code...

And in doing this write up and diving deeper into the problem...I found the issue! 

The server is looking for another header that was not present in my test requests, and that's why it was responding with a 401 `www-authenticate Negotiate, NTLM`. That point number 8 above is what led me to finding out what's happening...was misled for a while there :( 
Thanks for the help, and a good library....gonna leave the above analysis here for posterity :)

**Comment by aateeque** [comment]
And for completeness, I think the reason for the exception in the issue is that the buffer was the wrong size....causing a corrupt token which is [`SEC_E_INVALID_TOKEN`](https://docs.microsoft.com/en-us/windows/win32/secauthn/initializesecuritycontext--negotiate) here. Btw any way to return these actual codes?
