### ISSUE TITLE
Koa sample is not working

### ISSUE THREAD

**Issue by alberto-wagner** [jlguenego/node-expose-sspi#27]
Running the simple koa sample using koa@2.13.0 is failing with 404 error and Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client.

The Active Directory and authentication is working: I can get data into ctx.req.sso. Unfortunately everything after the handshake is broken with koa responding with 404, sending headers that conflicts with the setHeaders for 'WWW-Authenticate'.

**Comment by jlguenego** [comment]
I confirm ;)

When I did it, I have been testing just on a machine without Active Directory Domain Controller. Now I do the test with it and I see the same thing as you. I work on it and come back to you.

**Comment by jlguenego** [comment]
Fixed. I had to make a real async middleware.

```
import 'source-map-support/register';
import Koa from 'koa';
import { sso } from 'node-expose-sspi';
import { NextFunction } from '../../src/sso/interfaces';
const app = new Koa();

const auth = sso.auth();

const authPromise = (
  ctx: Koa.ParameterizedContext<Koa.DefaultState, Koa.DefaultContext>
): Promise<void> => {
  return new Promise<void>((resolve, reject) => {
    const next: NextFunction = (err?: Error) => (err ? reject(err) : resolve());
    auth(ctx.req, ctx.res, next);
  });
};

app.use(async (ctx, next) => {
  await authPromise(ctx);
  next();
});

app.use((ctx) => {
  ctx.body = ctx.req.sso;
});

app.listen(3000, () => console.log('Koa started on port 3000'));

```

**Comment by jlguenego** [comment]
@alberto-wagner Please test and close if ok.

**Comment by alberto-wagner** [comment]
Ok, I'll test it today! Thank you!

**Comment by MrDrannoc** [comment]
Hello, can't I use this with koa from JS only from TS?

**Comment by jlguenego** [comment]
Of course you can use it from JS as well.
