### ISSUE TITLE
how to use the client?

### ISSUE THREAD

**Issue by Aymkdn** [jlguenego/node-expose-sspi#3]
Hi,

I created a Node script to connect to a web server (that is not a Express server and that I don't control), This webserver needs Kerberos authentication. On a page I'll receive a 401 code with a header `www-authenticate` that has the value **Negociate**. From there, can I use your [`sso.client`](https://github.com/jlguenego/node-expose-sspi/blob/master/doc/use-case/client.md) to handle the authentication handshake with the server for me?

What I've done so far:
```javascript
const request = require('request'); // the one I use for the other requests
const { sso } = require('node-expose-sspi');

async function run() {
[... do a few request then handle the response ...]
  if (response.headers['www-authenticate'] === 'Negotiate') {
      console.log("Start Kerberos Authentication");
      try {
        const { fetch } = sso.client;
        const res = await fetch(uri, {
          headers:headers // here I pass headers including 2 cookies: `JSESSIONID` and `PF`
        });
        console.log("Fetch completed"); // <- I never reach this point?!
        let resBody = await res.text();
        console.log(resBody);
      } catch(err) {
        console.log("ERROR => ",err);
      }
  }
}
```

Two issues here:
1. I use https://httptoolkit.tech/javascript to intercept the requests and see what's going on: I can see that a request is done on behalf of your `fetch`, but I don't see any special headers or cookies that are sent (it just replicates my first request), so the server replies the same 401 with `www-authenticate; Negociate` than before… What I'm missing here?
2. I never reach `"Fetch Completed"`… my Node script just stop?!

Merci !

**Comment by jlguenego** [comment]
Hi,

Thanks for your feedback.
In the Negotiate protocol, here is what is happening:
1. the first request from the client has nothing particular in it.
2. the server responds status 401 with a header `www-authenticate: Negotiate` 

At this step, if the client tries again from scratch the same request (1), then it will receive the same request (2). So your code looks correct by trying to use the `node-expose-sspi` fetch API.

3. the client sends the same request, but with added header `Authorization: Negotiate xxxxx` with xxxxx is a base64 token (NTLM or Kerberos token).
4. the server should answer in all case something... which is your main issue.

- NTLM: normally with header `www-authenticate: Negotiate yyyyy` where yyyyy is a NTLM token
- Kerberos: normally 200 OK with the protected resource.

5. NTLM only : the client sends again a same request with `Authorization: Negotiate zzzzz` with `zzzzz` is the third NTLM token.
6. the server respond 200 OK with the protected resource.

**If your server does not answer, this is not good from it: at least it should respond with a 400 bad request if the request was bad.**

Is it possible you investigate on your server side ?

Is it possible you investigate with curl (which support the NTLM/Kerberos protocol) or with a Google Chrome browser ?

Is it possible you send me the server for me to test ?

Hope this help.

**Comment by Aymkdn** [comment]
Thanks for the quick reply!

It's my company server, so no I cannot share it… The server works perfectly fine (we use it with the browsers). I need to access resources using Node, and to access these resources I need to be authenticated.

My problem is that your `fetch` doesn't add anything to the header of the request. It sends the request to the correct URL, but no changes happened to the headers. It's why I'm asking if I missed something in my code? And the server correctly replies to your `fetch` request with a 401 with `'www-authenticate: Negotiate'`, but there is no follow-up requests done.

The request that is done by your `fetch`
> GET https://my.company.com/idp/V34yM/resume/idp/prp.ping  
> Cookies: JSESSIONID=h33dlk7e2rne2d8xy3atyybr; PF=2m5juOhoXT2nl4blr6AcHbsqOoZaB79d9seBMfx24C0W;   

Response from the server:
> date: 'Thu, 02 Apr 2020 10:40:14 GMT',  
> 'referrer-policy': 'origin',
> 'cache-control': 'no-cache, no-store',  
>  pragma: 'no-cache',  
>  expires: 'Thu, 01 Jan 1970 00:00:00 GMT',  
>  'content-type': 'text/html;charset=utf-8',  
>  'www-authenticate': 'Negotiate',  
>  'set-cookie': [ 'PF=2m5juOhoXT2nl4blr6AcHbvWv0LW7oO0I03bp8Aq4eGX;Path=/;Domain=.company.com;SameSite=None;Secure;HttpOnly' ],  
>  'transfer-encoding': 'chunked'

And then nothing more happens…

**Comment by jlguenego** [comment]
OK I understand better. I was thinking the node-expose-sspi fetch was sending at least the first NTLM/Kerberos token.

I think I know what it is... May be the header is not properly recognized because of uppercase in `www-authenticate` keyword. I am going to insure this. I come back with a new version.

**Comment by Aymkdn** [comment]
Thanks!

I could try to debug your code (`client.ts`) to see what's going on, but I'm not able to compile your code once I did some changes in `client.ts`.

To build your code I did this:
```bash
$ cd ./node_modules/node-expose-sspi/
$ npm install
$ npm run build:ts
$ npm run build
```

On the last one I receive multiples errors `Cannot open include file: 'atlstr.h': No such file or directory` :( I'm not familiar with `node-gyp`

**Comment by jlguenego** [comment]
Yes, I know this error (atlstr.h). In fact, I don't have it if you install the Visual Studio normally.
But to go faster, just take the ./node_modules/node-expose-sspi/lib/api.node and you will be all set.

**Comment by Aymkdn** [comment]
> But to go faster, just take the ./node_modules/node-expose-sspi/lib/api.node and you will be all set.

I'm not sure to understand what to do with `api.node`?

**Comment by jlguenego** [comment]
I did a new version. With logs.
just do `npm i node-expose-sspi@latest`

Then to use debug: please do in a cmd: `set DEBUG=node-expose-sspi:client`
And run your program. Send me the logs ;)

**Comment by Aymkdn** [comment]
First, I needed to upgrade my Node from v10 to v12 to install the latest version of `node-expose-sspi`.

With the new version, your `fetch` replies to the server with an additional header `authorization: Negotiate YIIBa[…]`, and the server replies with `200 OK`

The debug:
```
node-expose-sspi:client handleAuth: start. headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    date: [ 'Thu, 02 Apr 2020 13:38:42 GMT' ],
    'referrer-policy': [ 'origin' ],
    'cache-control': [ 'no-cache, no-store' ],
    pragma: [ 'no-cache' ],
    expires: [ 'Thu, 01 Jan 1970 00:00:00 GMT' ],
    'content-type': [ 'text/html;charset=utf-8' ],
    'www-authenticate': [ 'Negotiate' ],
    'set-cookie': [
      'PF=Gv8vw9k8E08Z06QU2av8jtG8LUM7casp9B55p56Tpu2H;Path=/;Domain=.company.com;SameSite=None;Secure;HttpOnly'
    ],
    connection: [ 'close' ]
  }
} +0ms
  node-expose-sspi:client starting auth +16ms
  node-expose-sspi:client handleAuth: end +1s

<!DOCTYPE html>
<!-- template name: kerberos.only.error.template.html -->
<html lang="en" dir="ltr">
  <head>
    <title>Kerberos Authentication Error</title>
    <meta name="robots" content="noindex, nofollow" />
    <base href="$HttpServletRequest.getScheme()://$HttpServletRequest.getServerName():$HttpServletRequest.getServerPort()"/>
    <meta http-equiv="refresh" content="0" />
    <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link rel="stylesheet" media="all" type="text/css" href="assets/css/main.css" />
  </head>
  <body>
    <div class="ping-container">
      <div class="ping-header">
      </div><!-- .ping-header -->
      <div class="ping-body-container">
        <!--<h1>Kerberos Authentication Error</h1>-->
        <!-- Resume url is available for use to aid in recovery from this error state. -->
        <!-- /idp/yYdgT/resume/idp/prp.ping -->
      </div><!-- .ping-body-container -->
    <div class="ping-footer-container">
        <div class="ping-footer">
            <div class="ping-credits"/>
        </div> <!-- .ping-footer -->
    </div> <!-- .ping-footer-container -->
    </div><!-- .ping-container -->
  </body>
</html>
```

Regarding the headers, for the request:
> GET https://my.company.com/idp/V34yM/resume/idp/prp.ping  
> Cookies: JSESSIONID=h33dlk7e2rne2d8xy3atyybr; PF=2m5juOhoXT2nl4blr6AcHbsqOoZaB79d9seBMfx24C0W;   
> accept: */* 
> accept-encoding: gzip,deflate  
>  user-agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3)  
> authorization: Negotiate YIIBaAYGKwYBBQUCoIIBXDCCAVigGjAYBgorBgEEAYI3AgIeBgorBgEEAYI3AgIKooIBOASCATRORUdPRVhUUwAAAAAAAAAAYAAAAHAAAAC6N/lFuJTUTfCC3HX84Yi/porRTXaRtn2jGTcIX2kcDKHL2Z0V2mKDXI0dxtD6Fv0AAAAAAAAAAGAAAAABAAAAAAAAAAAAAABcM1MN6vkNTbLsSuN4bsM[…]HMAIABbADIAMAAxADkAXaEoMCagERsPV0VMTEtOT1dOOlBLVTJVoREwD6ADAgGAoQgwBhsEa2lraQ==

And the response:
> STATUS: 200 OK  
> cache-control: no-cache, no-store  
> content-type: text/html;charset=utf-8  
> date: Thu, 02 Apr 2020 13:37:08 GMT  
> expires: Thu, 01 Jan 1970 00:00:00 GMT  
> pragma: no-cache
> referrer-policy: origin
> set-cookie: PF=7hINtf0cUOeZcvYrplEmsa9X5FVFndIK8zrRUv0fHbAzf;Path=/;Domain=.company.com;SameSite=None;Secure;HttpOnly

**Do you think it worked?!**

When you say:
> Kerberos: normally 200 OK with the protected resource.

What do you mean by _protected resource_? As I'm not sure if the authentication worked here and what the server is supposed to send me back that I could use for the next requests :)

**Comment by jlguenego** [comment]
We progress... 😃 

Now the `node-expose-sspi` plays the Kerberos scenario.

So the fetch client sends the Kerberos token (that always starts with `YII...`. The kerberos token is correctly parsed, but the server does not accept it (Kerberos Authentication Error). May be it is a problem of not having sufficient privileges ?

Yes for the requirement. `node-expose-sspi` needs Microsoft Windows OS, NodeJS version >=12.16.1.

Suggestion: can you try from a powershell with your server the following:
```
Invoke-WebRequest -uri http://localhost:3001 -UseDefaultCredentials
```

replace the uri by yours.

**Comment by Aymkdn** [comment]
I have no problem to be authenticated when I use Chrome or IE… So why it would be insufficient privileges?

I used the below command:
> Invoke-WebRequest -uri https://my.company.com/idp/6Ei5G/resume/idp/prp.ping -UseDefaultCredentials

But I received the error _The request was aborted: Could not create SSL/TLS secure channel._ Hopefully I found [a fix](https://stackoverflow.com/a/41618979/1134119)!

Next it returns a _200 OK_, but with a Page Expired, because the URL always changes (you can see the `6Ei5G` is different). Never easy :-(

```html
StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html>


                    <!-- template name: state.not.found.error.page.template.html -->


                    <html lang="en" dir="ltr">
                    <head>
                        <title>Page Expired</title>
                        <meta name="robots" content="noindex...
RawContent        : HTTP/1.1 200 OK
                    Referrer-Policy: origin
                    Content-Security-Policy: script-src 'unsafe-inline' 'unsafe-eval' 'self'; img-src 'self'; style-src 'self' 'unsafe-inline'; base-uri 'self'; object-src 'self'...
Forms             : {}
Headers           : {[Referrer-Policy, origin], [Content-Security-Policy, [Pragma, no-cache], [Content-Length, 1760]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 1760
```

**Comment by Aymkdn** [comment]
There is a new cookie (called `PF`) that is sent for each request. I have the feeling your `fetch` doesn't get the `set-cookie` from the server's reponse and doesn't send the new cookie back to the server along with the `www-authenticate`…

Do you see what I mean?

**Comment by Aymkdn** [comment]
If I could compile your code, then I could try things… But I still stuck with `Cannot open include file: 'atlstr.h': No such file or directory`. I tried to install Visual Studio Community, but no luck…

**Comment by Aymkdn** [comment]
Thank you!

I'd like to try things and debug `client.ts` in the meantime…

After installating VS2017 Pro, and after opening `.\build\binding.sln`, VS has installed the missing librairies… Then by opening a `x86_x64 Cross Tools Command PRompt for VS 2017` prompt, I've been able to execute `npm run build` without errors 😅

However my changes in `client.ts` are not reflecting. Could you please explain me how to make my changes visible? I usually just modify a `.js` file to make it work, but here it seems more complicated! 

I'm just doing `npm run build:ts` and then `npm run build`…

Thank you in advance for any guidance!

**Comment by Aymkdn** [comment]
I found how to debug it: `npm run build:ts` and then I modified `build\client.js` (too much difficult for me to change the TypeScript versus the JavaScript)!

I can confirm that we need `set-cookie` to be passed each time to make it work.

I'll also need to define the `fetch` options, like adding [options `follow:0` and `redirect:'manual'`](https://github.com/node-fetch/node-fetch#options). I've hard-written it in the `client.js`, but maybe the below code will work???
```javascript
const res = await fetch(uri, {
  headers:headers,
  follow:0,
  redirect:'manual'
});
```

I'm now able to get an HTML page of type `html.form.login.template.html` that I need to analyse to find the next step!

I'm looking forward to your fix :-)

Enjoy your week-end!

**Comment by jlguenego** [comment]
I updated the C++ code in order to not rely anymore on `atlstr.h`.
So the `npm i -g windows-build-tools` should be ok.

**Comment by jlguenego** [comment]
Note : For compiling the typescript you can also use `npm run build:tsw` who add a watcher. So everytime you update the .ts file, it recompiles the .js files.

**Comment by jlguenego** [comment]
I have added the cookie handling. Please test with the new version : 0.1.8
Hope we get closed to your use case ;)

**Comment by jlguenego** [comment]
Please note that the API is updated. 

`const response = await new sso.Client().fetch('http://localhost:3000');`

**Comment by Aymkdn** [comment]
Thanks for the update. It doesn't seem to work… I'll try to debug it today and I'll let you know!

**Comment by Aymkdn** [comment]
For some reasons, the `npm run build:ts` and `npm run build:tsw` only compile `index.ts` to `dist/index.js` but not the other files… I'm currently trying to understand why and how to compile the files properly…

**Comment by jlguenego** [comment]
Check that `npm run build:tsw` is run from the `node-expose-sspi` directory.

**Comment by Aymkdn** [comment]
It's all OK now! Thank you very much for the quick fix! It's super useful!

Nothing to add or change, everything looks good to me! Well done 👍

**Comment by jlguenego** [comment]
Great ! Happy coding 😃
