### ISSUE TITLE
Client is silently failing at line 209 

### ISSUE THREAD

**Issue by visgotti** [jlguenego/node-expose-sspi#32]
`const clientCred = sspi.AcquireCredentialsHandle(credInput);
`

When I'm debugging, this line triggers my node program to terminate with an error but does not give any error message. 

I'm trying to authenticate a node app, I'm following the example pretty much to a T. 

I do not have an issue when trying to hit endpoints in my browser, but from a node cli I am struggling. 

When I log out credInput, it is 
```

{
    packageName: 'Negotiate',
   credentialUse: 'SECPKG_CRED_OUTBOUND'
}
```

**Comment by visgotti** [comment]
Needed to upgrade my node version- non issue.

**Comment by jlguenego** [comment]
added a control on node version for a better error checking. I hope nobody will throw again this kind of issue ;)
This is to improve the dev experience.
