### ISSUE TITLE
sso.authIsReady is undefined

### ISSUE THREAD

**Issue by StuartLoria** [jlguenego/node-expose-sspi#5]
When you follow the example using node 12.16.1, express ^4.17.1 and node-expose-sspi ^0.1.14 the authIsReady function is not defined

**Comment by jlguenego** [comment]
Oups. Documentation is a little bit late. I am going to fix that.

**Comment by jlguenego** [comment]
It is done, on the master branch. So you should see it.
Tell me if it is ok :relaxed:

**Comment by StuartLoria** [comment]
I tested it, I saw the base64 strings being generated but it did not work (I tested against the same URLs using another component from another author and it worked).
I documented the details on another issue, I think the kerberos ticket that is generated does not have the right information for some reason.

**Comment by jlguenego** [comment]
ok, I close this issue about documentation. The kerberos issue is the subject about the issue #6
