### ISSUE TITLE
NTLM Authentication doesn't seem to work in node.js

### ISSUE THREAD

**Issue by tomika** [jlguenego/node-expose-sspi#50]
The NTLM authentication doesn't seems to work at all in nodejs (12.19.0)

In Windows 10 Pro x64 built in IIS configured to accept NTLM (works with any browser).

To reproduce:
const sso = require("node-expose-sspi");
const x = new sso.Client();
x.setSSP("NTLM");
x.setCredentials("", "username", "password");
x.fetch("https://localhost/").then(r =>console.log(r.status)).catch(e => console.error(e));

I've tried to access other Microsoft webservers also, the result is the same.
I've set env variable `DEBUG=node-expose-sspi:*`. but got no more log.
I've debugged the program, everything seems to be alright, but after sending NTLM 3 type message IIS refuses it with another 401 HTTP status code instead of responding 200.

I've compared the parsed NTLM messages (browser and nodejs) the only significant difference I see is that node-expose-sspi's NTLM 3 message doesn't containts Session Key member while the browser's version has a 16 bytes long session key. (Negotiate Key Exchange also missing of course)

OS: Windows 10 Pro version 19041.572 x64]
Browser version: Chrome  86.0.4240.111
Node version and architecture: 12.19.0 64 bits

 - Are you on a Windows domain: no
 - Can you reach the domain controller: no
 - Do your session have admin privileges: no
 - Which authentication protocol: NTLM

**Comment by jlguenego** [comment]
Hello,

Look at the example https://github.com/jlguenego/node-expose-sspi/tree/master/examples/client-runas

You will see that when your need to put "LOCAL" for the domain:
```
x.setCredentials("", "username", "password");
```

Could you close the defect if that solves your issue ? Thanks.

And enjoy this module ;)

**Comment by tomika** [comment]
Hi,

I'm very sorry, but I tried to set "LOCAL" as domain parameter and it 
doesn't work for me.

I tried with your code also:

b:\sspi_test>node client_runas.js --url http://localhost -d LOCAL -u 
Tomika -p ****
Error: fetch returned response with error 401
     at main (b:\sso_test\index.js:59:13)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)

Üdv,
/TT

2020. 10. 25. 10:34 keltezéssel, Jean-Louis GUENEGO írta:

**Comment by jlguenego** [comment]
There is a example project inside node-expose-sspi: https://github.com/jlguenego/node-expose-sspi/tree/master/examples/client-runas

Can you check with it if it is working or not with your IIS.

Other question ? How did you managed to get the SSL on you IIS : https://localhost ? Please give me the detail.
And have you done something special to have NTLM working on your IIS ? Can you describe or give doc url ? Thanks.

**Comment by jlguenego** [comment]
I added a new version (0.1.51) which has been tested with IIS. Please try it.

**Comment by tomika** [comment]
It is now working, thx

**Comment by tomika** [comment]
Sorry, I did not answer the question: https was a mistype, I tried it with plain http.
