### ISSUE TITLE
authenticated status

### ISSUE THREAD

**Issue by jgmurray23** [jlguenego/node-expose-sspi#55]
This isn't a bug report so much as a question. I am getting a 400 status back, but I *think* I am getting authenticated correctly, I'm just not talking to the service the right way. I am using your library to have node connect to a 'Business Central' OData instance. 

I'm running node 12 on windows 10 and my machine is NOT on the same domain as the server. 

---

var { sso } = require('node-expose-sspi');

var url = 'http://abc123host.internal:7048/BL_BC140CU01/OData/$metadata';

( async ()=> {

    try {

        sso.auth({
            useOwner: false,
            useActiveDirectory: true,
            useCookies: false,
            domain:'JM',
        }) ;

        const client = new sso.Client();
        client.setCredentials ('domain','user', 'pass');
        client.setSSP('NEGOTIATE');
      
     console.log( sso.getStatusInfo() );

     const resp1 = await  client.fetch(url) ;
     
    console.log('resp1', resp1 );

    }catch(e){
        console.log('#####ERR', e);
    console.log(e);
}
})();

-----

The 'Authorization: Negotiate TlRMTVNTUAACAAAACgAKADgAA......

makes me think it HAS authorized correctly. I would get a 401 back if it didn't I assume?

{ adminPrivileges: false, isOnDomain: false, domain: 'ZIPPY' }
  node-expose-sspi:client start response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    'www-authenticate': [ 'Negotiate' ],
    date: [ 'Wed, 11 Nov 2020 20:08:20 GMT' ],
    connection: [ 'close' ]
  }
} +0ms
  node-expose-sspi:client cookieList:  {} +3ms
  node-expose-sspi:client starting negotiate auth +0ms
  node-expose-sspi:client input:  {
  credential: '0x0000015e432f07b0.0x0000022f3ad54eb0',
  targetName: 'HTTP/qds-navmhwk03.JM.internal',
  cbMaxToken: 48256,
  targetDataRep: 'SECURITY_NATIVE_DREP'
} +2ms
  node-expose-sspi:client first requestInit.headers {
  Authorization: 'Negotiate TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAKAGFKAAAADw=='
} +5ms
  node-expose-sspi:client first response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    'www-authenticate': [
      'Negotiate TlRMTVNTUAACAAAACgAKADgAAAAVgoniv88d9Dcm7LAAAAAAAAAAALgAuABCAAAACgBjRQAAAA9RAEkAWABBAFMAAgAKAFEASQBYAEEAUwABABoAUQBEAFMALQBOAEEAVgBNAEgAVwBLADAAM
wAEABwAcQBpAHgAYQBzAC4AaQBuAHQAZQByAG4AYQBsAAMAOABRAEQAUwAtAE4AQQBWAE0ASABXAEsAMAAzAC4AcQBpAHgAYQBzAC4AaQBuAHQAZQByAG4AYQBsAAUAHABxAGkAeABhAHMALgBpAG4AdABlAHIAbgB
hAGwABwAIACjE+2ZmuNYBAAAAAA=='
    ],
    date: [ 'Wed, 11 Nov 2020 20:08:20 GMT' ],
    connection: [ 'close' ]
  }
} +199ms
  node-expose-sspi:client cookieList:  {} +3ms
  node-expose-sspi:client other requestInit.headers {
  Authorization: 'Negotiate TlRMTVNTUAADAAAAGAAYAHwAAAB+AX4BlAAAAAoACgBYAAAAEAAQAGIAAAAKAAoAcgAAABAAEAASAgAAFYKI4goAYUoAAAAPKPaMbj/9si8k8JkIau909lEAaQB4AGEAcwBRAH
cAYQBuAHQAaQBmAHkAWgBJAFAAUABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJ/SXVc3MBAOOkU9xngqu9ABAQAAAAAAACjE+2ZmuNYBnJZAJ/rnoKkAAAAAAgAKAFEASQBYAEEAUwABABoAUQBEAFMALQBOAEEA
VgBNAEgAVwBLADAAMwAEABwAcQBpAHgAYQBzAC4AaQBuAHQAZQByAG4AYQBsAAMAOABRAEQAUwAtAE4AQQBWAE0ASABXAEsAMAAzAC4AcQBpAHgAYQBzAC4AaQBuAHQAZQByAG4AYQBsAAUAHABxAGkAeABhAHMALg
BpAG4AdABlAHIAbgBhAGwABwAIACjE+2ZmuNYBBgAEAAIAAAAIADAAMAAAAAAAAAABAAAAACAAAEbEIFqOY7gLT8Z0cXmgo5IMZz00azmjLMcq/LbdXof8CgAQAAAAAAAAAAAAAAAAAAAAAAAJAEIASABUAFQAUAAv
AHEAZABzAC0AbgBhAHYAbQBoAHcAawAwADMALgBxAGkAeABhAHMALgBpAG4AdABlAHIAbgBhAGwAAAAAAAAAAAArJ4CcTLZtoXOXUllFUUMP'
} +3ms
  node-expose-sspi:client other response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    date: [ 'Wed, 11 Nov 2020 20:08:20 GMT' ],
    connection: [ 'close' ]
  }
} +262ms
  node-expose-sspi:client cookieList:  {} +3ms
  node-expose-sspi:client handleAuth: end +1ms
resp1 Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object],
      [Symbol(kCapture)]: false
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://qds-navmhwk03.JM.internal:7048/BL_BC140CU01/OData/$metadata?$format=json',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}

**Comment by jlguenego** [comment]
sso.auth() can only be used on the server side. Apparently you want to code an HTTP client.

**Comment by jgmurray23** [comment]
Yes that's correct. I have tried the client example with similar results. Is this a library I can use as an http client? I saw fetch in there. Or am I wrong :( ?

**Comment by jlguenego** [comment]
Yes this module can be used for both client and server.

**Comment by jgmurray23** [comment]
I"ve attempting to get a similar response that I would see using curl - for example:

curl -vvvv --negotiate -u Qwantify:crazypass http://qds-navmhwjm.jm.internal:7058/AD_BC140CU01/OData/

I get a 200 back and some data

I tried the following to 'replicate' what I see with curl - but I don't think I"m doing it right. I set it to 'Negotiate' and provide user/pass/url - but I get a 400 back

const { sso } = require('node-expose-sspi');
const yargs = require('yargs');
const dbg = require('debug');
const debug = dbg('node-expose-sspi:client');


const myArgv = yargs
    .usage('$0 [url]', 'Request a url (by default http://localhost:3000)')
    .option('url', {
        type: 'string',
        description: 'Absolute url',
        default: 'http://localhost:3000',
    })
    .option('user', {
        alias: 'u',
        type: 'string',
        description: 'Run as user',
        default: '',
    })
    .option('password', {
        alias: 'p',
        type: 'string',
        description: 'user password',
        default: '',
    })
    .help()
    .alias('h', 'help').argv;

async function main(argv) {

    debug('argv: ', argv);
    const client = new sso.Client();

    try {
            client.setCredentials('', argv.user, argv.password );
            client.setSSP('Negotiate');
            const response = await client.fetch( argv.url ) ;
            console.log('response', response.status ) ;


    } catch (e) {
        console.error(e);
    }
}
main(myArgv);


C:\Users\joe\IdeaProjects\qwantifyqixas\src>node client2 'http://qds-navmhwk03.qijm.internal:7058/AD_BC140CU01/OData/' -u 'Qwantify' -p 'crazypass'
  node-expose-sspi:client argv:  {
  _: [],
  u: 'Qwantify',
  user: 'Qwantify',
  p: 'Q!xasQw4N!4#2',
  password: 'Q!xasQw4N!4#2',
  url: 'http://qds-navmhwk03.qijm.internal:7058/AD_BC140CU01/OData/',
  '$0': 'client2'
} +0ms
  node-expose-sspi:client start response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    'www-authenticate': [ 'Negotiate' ],
    date: [ 'Fri, 13 Nov 2020 03:28:12 GMT' ],
    connection: [ 'close' ]
  }
} +0ms
  node-expose-sspi:client cookieList:  {} +5ms
  node-expose-sspi:client starting negotiate auth +1ms
  node-expose-sspi:client Client running on a host that is not part of a Microsoft domain +8ms
  node-expose-sspi:client input:  {
  credential: '0x0000015e42ea7940.0x00000263769cb780',
  targetName: 'whatever',
  cbMaxToken: 48256,
  targetDataRep: 'SECURITY_NATIVE_DREP'
} +1ms
  node-expose-sspi:client first requestInit.headers {
  Authorization: 'Negotiate TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAKAGFKAAAADw=='
} +8ms
  node-expose-sspi:client first response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    'www-authenticate': [
      'Negotiate TlRMTVNTUAACAAAACgAKADgAAAAVgoniQ8Gn/aOjbo0AAAAAAAAAALgAuABCAAAACgBjRQAAAA9RAEkAWABBAFMAAgAKAFEASQBYAEEAUwABABoAUQBEAFMALQBOAEEAVgBNAEgAVwBLADAAM
wAEABwAcQBpAHgAYQBzAC4AaQBuAHQAZQByAG4AYQBsAAMAOABRAEQAUwAtAE4AQQBWAE0ASABXAEsAMAAzAC4AcQBpAHgAYQBzAC4AaQBuAHQAZQByAG4AYQBsAAUAHABxAGkAeABhAHMALgBpAG4AdABlAHIAbgB
hAGwABwAIAPJedARtudYBAAAAAA=='
    ],
    date: [ 'Fri, 13 Nov 2020 03:28:12 GMT' ],
    connection: [ 'close' ]
  }
} +224ms
  node-expose-sspi:client cookieList:  {} +4ms
  node-expose-sspi:client other requestInit.headers {
  Authorization: 'Negotiate TlRMTVNTUAADAAAAGAAYAHIAAABMAUwBigAAAAAAAABYAAAAEAAQAFgAAAAKAAoAaAAAABAAEADWAQAAFYKI4goAYUoAAAAPuVxb6R6jOwCzTXEdyYIxC1EAdwBhAG4AdABpAG
YAeQBaAEkAUABQAFkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvAWyqsCkcv7C4d4WaEb5bwEBAAAAAAAA8l50BG251gH6Nnj3cmwzkgAAAAACAAoAUQBJAFgAQQBTAAEAGgBRAEQAUwAtAE4AQQBWAE0ASABXAEsA
MAAzAAQAHABxAGkAeABhAHMALgBpAG4AdABlAHIAbgBhAGwAAwA4AFEARABTAC0ATgBBAFYATQBIAFcASwAwADMALgBxAGkAeABhAHMALgBpAG4AdABlAHIAbgBhAGwABQAcAHEAaQB4AGEAcwAuAGkAbgB0AGUAcg
BuAGEAbAAHAAgA8l50BG251gEGAAQAAgAAAAgAMAAwAAAAAAAAAAEAAAAAIAAARsQgWo5juAtPxnRxeaCjkgxnPTRrOaMsxyr8tt1eh/wKABAAAAAAAAAAAAAAAAAAAAAAAAkAEAB3AGgAYQB0AGUAdgBlAHIAAAAA
AAAAAADyQzMAG5RTS9RDHGO97n8R'
} +6ms
  node-expose-sspi:client other response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    date: [ 'Fri, 13 Nov 2020 03:28:12 GMT' ],
    connection: [ 'close' ]
  }
} +288ms
  node-expose-sspi:client cookieList:  {} +2ms
  node-expose-sspi:client handleAuth: end +1ms
response 400



Can you see anything obvious I'm doing wrong? I'm running node 12 ( and curl ) on the same workstation - and I don't control the IIS business central side

**Comment by jlguenego** [comment]
node 12 may not be enough. Check better the version. Requirements: Microsoft Windows OS, NodeJS version >=12.16.1. Architecture: x64 or ia32.

Have you tried the client-runas example itself ?

**Comment by jgmurray23** [comment]
node v12.18.3 - I will try the  exact client-runas example next and report back.

**Comment by jgmurray23** [comment]
I tried with and without domain. No luck yet! 


C:\Users\joe\IdeaProjects\qwantifyqixas\src>node client-runas 'http://qds-navmhwk03.qixas.internal:7058/AD_BC140CU01/OData/' -u 'Qwantify' -
p 'Q!xasQw4N!4#2'
  node-expose-sspi:client argv:  {
  _: [],
  u: 'Qwantify',
  user: 'Qwantify',
  p: 'Q!xasQw4N!4#2',
  password: 'Q!xasQw4N!4#2',
  url: 'http://qds-navmhwk03.qixas.internal:7058/AD_BC140CU01/OData/',
  domain: '',
  d: '',
  '$0': 'client-runas'
} +0ms
  node-expose-sspi:client start response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    'www-authenticate': [ 'Negotiate' ],
    date: [ 'Fri, 13 Nov 2020 16:27:25 GMT' ],
    connection: [ 'close' ]
  }
} +0ms
  node-expose-sspi:client cookieList:  {} +5ms
  node-expose-sspi:client starting negotiate auth +1ms
  node-expose-sspi:client Client running on a host that is not part of a Microsoft domain +7ms
  node-expose-sspi:client input:  {
  credential: '0x0000015e426ffe10.0x0000022212b8c920',
  targetName: 'whatever',
  cbMaxToken: 48256,
  targetDataRep: 'SECURITY_NATIVE_DREP'
} +1ms
  node-expose-sspi:client first requestInit.headers {
  Authorization: 'Negotiate TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAKAGFKAAAADw=='
} +8ms
  node-expose-sspi:client first response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    'www-authenticate': [
      'Negotiate TlRMTVNTUAACAAAACgAKADgAAAAVgoniQB4Ev04IyKsAAAAAAAAAALgAuABCAAAACgBjRQAAAA9RAEkAWABBAFMAAgAKAFEASQBYAEEAUwABABoAUQBEAFMALQB
OAEEAVgBNAEgAVwBLADAAMwAEABwAcQBpAHgAYQBzAC4AaQBuAHQAZQByAG4AYQBsAAMAOABRAEQAUwAtAE4AQQBWAE0ASABXAEsAMAAzAC4AcQBpAHgAYQBzAC4AaQBuAHQAZQByAG4
AYQBsAAUAHABxAGkAeABhAHMALgBpAG4AdABlAHIAbgBhAGwABwAIAI9aDd/ZudYBAAAAAA=='
    ],
    date: [ 'Fri, 13 Nov 2020 16:27:25 GMT' ],
    connection: [ 'close' ]
  }
} +137ms
  node-expose-sspi:client cookieList:  {} +3ms
  node-expose-sspi:client other requestInit.headers {
  Authorization: 'Negotiate TlRMTVNTUAADAAAAGAAYAHIAAABMAUwBigAAAAAAAABYAAAAEAAQAFgAAAAKAAoAaAAAABAAEADWAQAAFYKI4goAYUoAAAAPJGpoD9oI7l7czFiA
mTCIjFEAdwBhAG4AdABpAGYAeQBaAEkAUABQAFkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0GJpIaXSTYGTpNOhBiQCBwEBAAAAAAAAj1oN39m51gHBvMBfBH39zwAAAAACAAoAUQBJ
AFgAQQBTAAEAGgBRAEQAUwAtAE4AQQBWAE0ASABXAEsAMAAzAAQAHABxAGkAeABhAHMALgBpAG4AdABlAHIAbgBhAGwAAwA4AFEARABTAC0ATgBBAFYATQBIAFcASwAwADMALgBxAGkA
eABhAHMALgBpAG4AdABlAHIAbgBhAGwABQAcAHEAaQB4AGEAcwAuAGkAbgB0AGUAcgBuAGEAbAAHAAgAj1oN39m51gEGAAQAAgAAAAgAMAAwAAAAAAAAAAEAAAAAIAAARsQgWo5juAtP
xnRxeaCjkgxnPTRrOaMsxyr8tt1eh/wKABAAAAAAAAAAAAAAAAAAAAAAAAkAEAB3AGgAYQB0AGUAdgBlAHIAAAAAAAAAAABetf+JR+4HB8huXSA0cjUT'
} +4ms
  node-expose-sspi:client other response.headers Headers {
  [Symbol(map)]: [Object: null prototype] {
    'content-length': [ '0' ],
    server: [ 'Microsoft-HTTPAPI/2.0' ],
    date: [ 'Fri, 13 Nov 2020 16:27:25 GMT' ],
    connection: [ 'close' ]
  }
} +238ms
  node-expose-sspi:client cookieList:  {} +2ms
  node-expose-sspi:client handleAuth: end +2ms
  node-expose-sspi:client response:  Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object],
      [Symbol(kCapture)]: false
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://qds-navmhwk03.qixas.internal:7058/AD_BC140CU01/OData/',
    status: 400,
    statusText: 'Bad Request',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
} +651ms
Error: fetch returned response with error 400
    at main (C:\Users\joe\IdeaProjects\qwantifyqixas\src\client-runas.js:59:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by jlguenego** [comment]
Hi, I just added a new version (0.1.51) and now the node-expose-sspi client is tested with IIS.
The problem was that I was not using a "keep-alive" connection. And IIS requires the keep alive connection for the Negotiate (Kerberos, NTLM) protocol.

Please give it a try.

**Comment by jgmurray23** [comment]
Success! C'est Bon! (forgive my crappy Canadian Highschool French)

**Comment by jlguenego** [comment]
Hello @jgmurray23 
I just wanted to say thank you: you are my first sponsor ! I really appreciated ;)
All what I deliver here is for free, but I really appreciate people who valuate my software.
Again thanks !
:heart:

**Comment by jgmurray23** [comment]
You saved me a *ton* of time - and this is excellent for my use case, so it only seems fair. Thx again.
