### ISSUE TITLE
Is it possible to force sso.auth to use NTLM over Kerberos? 

### ISSUE THREAD

**Issue by mhdraef** [jlguenego/node-expose-sspi#60]
I know this is possible using a client but is it possible to force the function to use only NTLM?

**Comment by jlguenego** [comment]
no, but I think I can add an option for this.
The `WWW-Authenticate` could be forced to use NTLM instead of Negotiate.
Will try to do it ;)

**Comment by jlguenego** [comment]
Done 😄 

version 0.1.53

Look at the unit test
https://github.com/jlguenego/node-expose-sspi/blob/master/test/server-ntlm.spec.ts

Please read the doc:
https://github.com/jlguenego/node-expose-sspi/blob/master/doc/reference/index.md#authoptions

I think you should know how to use it...
Just use the `forceNTLM` options.

Please close this issue if ok.

**Comment by mhdraef** [comment]
Works great, thank you.
