### ISSUE TITLE
BadRequestError: Error while doing SSO

### ISSUE THREAD

**Issue by acecoder93** [jlguenego/node-expose-sspi#7]
Working on running a simple script with express and node-expose-sspi on a Windows OS. When I use a client to ping the server, I get the following error: "BadRequestError: Error while doing SSO". The goal is to use Kerberos.

Also, using Google Chrome to do this and have whitelisted the domain.

**Comment by jlguenego** [comment]
I was working today on it, and I did some regression. Sorry for that. Please retest with the last version (0.1.23) and if you still have the bug, please do the following:

```
set DEBUG=node-expose-sspi:*
```

run your scenario and send the trace. Thanks.

**Comment by acecoder93** [comment]
Attached for your reference is the trace. Please note the environment is a Linux Client pinging a Windows server. The Windows server is running the script.
[trace.txt](https://github.com/jlguenego/node-expose-sspi/files/4477702/trace.txt)

**Comment by jlguenego** [comment]
From the trace.txt file, we can see that the Linux client is sending a Kerberos SPNEGO. The format of the Kerberos is ok, but the provided credentials are not. The SSPI microsoft message is "logon denied."
See the Microsoft explanation here :
https://docs.microsoft.com/fr-fr/windows/win32/secauthn/acceptsecuritycontext--negotiate

If your browser invites you to enter credentials, you must enter the username like this : DOMAIN\USERNAME

where DOMAIN is the NETBIOS Domain (the domain shortname)
and USERNAME is the windows domain account you want to use.

In the main time, I can try to do better error message to help user and improve the DX.

**Comment by jlguenego** [comment]
I spent some hours today installing a hyperv virtual machine with Linux Mint (Ubuntu, Debian). I followed some instructions for connecting DNS, Active Directory users. I am not an expert of this.

Interesting links (but there are many similar on the web):
- configuring Linux to connect it to the Windows domain : https://forums.linuxmint.com/viewtopic.php?f=47&t=237445&p=1264498&hilit=sssd+mdm#p1264498
- configuring chrome : https://akasurde.github.io/krb-auth-chrome.html

I logged with AD user, configured Google Chrome with some policies to use Kerberos, and it was really fine :smiley:

No error at all with node-expose-sspi 0.1.23


So I confirm we can connect from a Linux client to an HTTP server running node-expose-sspi.

**Comment by acecoder93** [comment]
Thank you for that information and for doing additional testing. It was successfully able to be tested after adjusting the realm name. Note, realm name is case-sensitive. In addition, node-expose-sspi 0.1.23 helped resolve the "error while doing sso" issue. Thank you for your help!

**Comment by jlguenego** [comment]
Happy that you have succeed as well. Enjoy the SSO with Kerberos ;)
