### ISSUE TITLE
When API rerouted in IIS with re-write module and site given a name Auth fails

### ISSUE THREAD

**Issue by MPNaresh** [jlguenego/node-expose-sspi#8]
The API keeps popping up user id and password window, if the server is running in port and IIS hosts an endpoint with re-write to server port + if the iis site has an alias name.

Example:
http://MySite

IIS
   Applications
         MySiteWeb -> GivenName MySite
         Rewrite 192.168.1.4:3000 ==> API hosted with node-expose-API

In this case in browser http://MySite it keeps popping 
log in

**Comment by jlguenego** [comment]
Hello MPNaresh,

The popup is not raised by the node-expose-sspi, but by the browser.
Most browsers (like Edge, Chrome, etc.) seem to always popup a dialog box to ask credentials in certain circumstances. This is independent of node-expose-sspi.

**If you are using Kerberos, it would not ask for credentials.** To use Kerberos on Windows with SSPI, the server and client both need to be joined to a [Windows Domain](https://en.wikipedia.org/wiki/Windows_domain).

When Kerberos cannot be used, windows browser will try to use the authentication protocol  **NTLM**, then it may open this popup. I can do nothing about that.

**Please answer to this questions for better analysis:**
1. What OS and browser do you use as the client?
2. Is the server machine joined to an Active Directory domain?
3. Is the IIS machine joined to an Active Directory domain?
3. Is the client machine joined to an Active Directory domain?
4. In your situation, IIS is acting as a reverse proxy? (yes/no)
5. What protocol do you plan to use? (Kerberos, or NTLM)

**Comment by MPNaresh** [comment]
Hi,
I understand that the pop up is from browser and its part of negotiations.
I do not specifically mention a protocol, so I guess this could be NTLM.
What OS and browser do you use as the client?
Is the server machine joined to an Active Directory domain?
Windows 10 client Chrome browser.
Windows 2012 server, IIS 7.5
Is the IIS machine joined to an Active Directory domain?
Yes
Is the client machine joined to an Active Directory domain?
Yes
In your situation, IIS is acting as a reverse proxy? (yes/no)
we are configuring a rule that, any calls to http://mySite should be redirected to 192.168.1.4:3000.

What protocol do you plan to use? (Kerberos, or NTLM)

I did not specify any of it. I think it used default.

Thank you,
-Naresh

**Comment by jlguenego** [comment]
Please indicate exactly where and how you configure this redirection rule.
Is it inside IIS Manager ? or in the DNS ?
Please put **all the details**.

I would like to reproduce your scenario. You can put screenshots. They are welcome.

Also, I would like you to setup trace in the node server, by setting `set DEBUG=node-expose-sspi:*`.
and then you attached here the trace output in a file.
Thanks,
JL

**Comment by jlguenego** [comment]
I have added a documentation for doing the scenario mentioned in this issue.

In your case, it is normal to have this popup. If you do not want the popup, you need to be in Kerberos. Make sure the user running the server has the correct SPN (Service Principal Name).

A SPN is always `HTTP/<hostname>`.

In your case, the SPN is `HTTP/MySite`. You can use the `setspn` microsoft command or go in ADUC (Active Directory Users and Computers) to set the SPN on the server user account.

https://github.com/jlguenego/node-expose-sspi/blob/master/doc/use-case/production-windows.md

**Comment by MPNaresh** [comment]
Please allow me a day more. I will reply

**Comment by jlguenego** [comment]
Considered as corrected.
