### ISSUE TITLE
Cannot input the keytab and principal in the library running on a Windows Server

### ISSUE THREAD

**Issue by nekyouto** [jlguenego/node-expose-sspi#85]
Was trying to implement Kerberos in my current project.

I was looking through the documentation and the README file. But couldn't find the necessary function that indicates the parsing of the principal and the keytab file. Am I missing something or this is going to be a feature to be supported in the future? Or is the code reading the keytab file from some other location in the Windows Environment under the hood?

**Comment by jlguenego** [comment]
Keytab, unfortunately, do not integrate with Microsoft SSPI interface. So it is not usable by the node-expose-sspi.
